### ISSUE TITLE
Playlists won't play

### ISSUE THREAD

**Issue by N0rbertas** [mp31415/DiskYT#4]
For some reason, when i try to play a playlist (ANY playlist) the site says that the playlist is currently playing, but for some reason - i always only get a 3 second long video titled "Black" which is just 3 seconds of nothingness. When I try to skip ahead or do pretty much anything, the video doesn't change. This is quite an issue since it sadly makes the site pretty much unusable for what I wanted to use it for. Any suggestions/fixes? Here's a screenshot of what it looks like:
![image](https://user-images.githubusercontent.com/44842847/61538227-9ae7f600-aa41-11e9-872d-dbc6dcafa230.png)

**Comment by mp31415** [comment]
Is there any public playlist where this problem is reproduced? 

Sometimes there are limitations on what can be played outside of the main YouTube site, i.e. video author may disallow watching/listening in an embedded player. In this case DiskYT cannot do much. 

Although for some playlist items there can be regional restrictions (but if you can watch/listen the same items on YouTube then it's probably not the case). 

Yet, another case is when some items are completely removed from YouTube (again, likely not your case).

**Comment by N0rbertas** [comment]
For me, this problem happens on every single playlist I try to play.

It doesn't seem like the limitations, regional restrictions, or items being removed from YouTube are the issue. I have no idea what it is.

**Comment by mp31415** [comment]
Thank you for reporting this.
It looks you are using Chrome browser in Windows. I just tried to create a few new playlists in Chrome in Windows 10 and it seems working. Could it be that your extra Chrome plugins (like Ad Blocker seen in your snapshot) conflict somehow with the embedded YouTube browser? Does it happen in other browsers?

**Comment by N0rbertas** [comment]
Very interesting. Yes, it was either my adblocker/pop-up blocker. I disabled them and now the site seems to work just fine. Thanks for the responses!
